### PR TITLE
Add a basic cookie store

### LINKED ISSUE #968: Auth: Cookies
This project _really_ needs to support storing and automatically re-sending cookies, just like a browser would.

I'll work on an PR for this:

I'll work on cookies [in my fork](https://github.com/Tanja-4732/bruno) since you seem to be working on auto-save.

I hope to have some progress by the end of the week; will (hopefully) open a draft-PR until then

_Originally posted by @Tanja-4732 in https://github.com/usebruno/bruno/discussions/385#discussioncomment-7571305_

### Tasks
- [x]  Basic Cookie Support
- [ ] CLI Support
- [x] Delete a cookie in UI
- [ ] Edit a cookie in UI
- [ ] Add a cookie in UI
- [ ] Add a new domain/url in UI

### PR DESCRIPTION
**Pull request by Tanja-4732**
# Description

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [ ] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.** #968 

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### My checklist

- [x] Figure out how this project is structured
- [x] Find a place/concept on where to put which new buttons/widgets
- [ ] Implement the cookie store (needs feedback for how to handle persistence)

---

closes #968

### CODE REVIEW

**Comment by Tanja-4732** [comment]
Some progress made already:

see https://github.com/usebruno/bruno/issues/968#issuecomment-1817329038

**Comment by Tanja-4732** [comment]
gotta love some good rebase :sparkles:

**Comment by Tanja-4732** [comment]
@helloanoop pls review; I hope the code works;

Tell me how to refactor & add screenshots/docu to meet the projects goals; thanks

**Comment by helloanoop** [comment]
Hi @Tanja-4732 

Appreciate all the work, but won't be able to get this in. Below are the issues

1. The PR considers cookies to be a collection level construct, where as we need it to be at the app level
2. The cookie implementation does not take into consideration the logic of mapping the cookies to domains. Also the expiry time of cookies

Since this a key feature and many folks are blocked, I went ahead and have implemented the cookie support https://github.com/usebruno/bruno/commit/e1a96e0f2356c46293b791b6a99a8552f20f1f1b

However, there is still a lot more work needed on cookie support, specially around adding, editing and deleting cookies.

**Comment by Tanja-4732** [comment]
@helloanoop 

Thanks for your efforts in

1. Reviewing my PR
2. Writing a "proper" implementation yourself

Do you think these additional changes should be made in a new PR?

**Comment by helloanoop** [comment]
@Tanja-4732 Yes, there is work left on adding, editing and deleting cookies.

Let's pick one at a time.

When you find some time, it'd be great of you could work on support for deleting cookies.
This would be basically a delete icon in each cookie row. Clicking on delete would delete the cookie in the cookie jar.

**Comment by helloanoop** [comment]
@Tanja-4732 Closing this PR.

In case you are working on support for deleting cookies, please sync your fork's main with `usebruno:main` and cut a new branch `feature/delete-cookies` for the delete cookie work

**Comment by Tanja-4732** [comment]
> @Tanja-4732 Closing this PR.
> 
> In case you are working on support for deleting cookies, please sync your fork's main with `usebruno:main` and cut a new branch `feature/delete-cookies` for the delete cookie work

Will do soon enough :+1: :sparkles:

**Comment by Tanja-4732** [comment]
> > @Tanja-4732 Closing this PR.
> > In case you are working on support for deleting cookies, please sync your fork's main with `usebruno:main` and cut a new branch `feature/delete-cookies` for the delete cookie work
> 
> Will do soon enough 👍 ✨

@helloanoop is this still relevant?

I could port my existing UI-work to your cookie implementation.

Should I?  
I'm just asking if that's already in the works or not

**Pull request closed without merging**
