### PR TITLE
Feat/displaying variable hints as secrets

### PR DESCRIPTION
**Pull request by Pragadesh-45**
fixes: #3265 

# Description

This PR addresses the issue of secret variables being displayed on hover in editor components by implementing the following logic:
 - Checks masked variables from environment variables, which support secret variables.
 - Verifies if lower-level variables (such as request or folder variables) override the secret variables, including cases with string interpolation.
 - Creates a (*****) node to hide secret values and prevent them from being displayed.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Before:
image

After:

https://github.com/user-attachments/assets/7319a8e0-8dae-465a-a35c-f8fa0712ac92

### CODE REVIEW

**Comment by fredx21** [comment]
Why do we want this? It's usefull to see the secrets.

**Comment by Pragadesh-45** [comment]
Hey @fredx21!

The intention of this PR is to hide secrets when hovering over variables in the Editor, particularly during cases like screen sharing. We thought that this [Discussion](https://github.com/usebruno/bruno/discussions/1645) made sense, as it suggests hiding the variable only if it is marked as a secret. In some cases, we can't guarantee whether a variable is a secret since it is displayed when accessed. This will provide users with a strict way to view all secret variables in the same place—in this case, the Environment variable section. All secret variables can be viewed and edited in that area.

PS: _I acknowledge that in some cases, it may be useful to show the secret variables. It's truly subjective, and I believe the discussion mentioned above made sense, especially when we're on a client call and want to avoid exposing secret variables. For example, I used `{{host}}` as a secret. In most cases, it will be things like API keys, passwords, and JWT tokens. However, I think using `{{host}}` as an example may have caused a misunderstanding of the feature._

**Comment by fredx21** [comment]
I understand that in some case it might be usefull to hide the secret variable, however, its more often usefull to have those secrets shown as this is mostly a developer-first tool. 

What do you think about adding a option in setting to allow user changing the default behavior?

**Comment by Pragadesh-45** [comment]
> What do you think about adding a option in setting to allow user changing the default behavior?

This one will work great. Thanks for the nice suggestion, by the way!

**Comment by helloanoop** [comment]
I have merged the PR.
@Pragadesh-45 please create a new github issue to track @fredx21 suggestion on adding a option in setting to allow user changing the default behavior.

**Pull request merged**
