### PR TITLE
feat: added active query, headers, vars and asserts count

### PR DESCRIPTION
**Pull request by therealrinku**
Added active params, headers, vars and assertions count on the request options tab

image

### CODE REVIEW

**Comment by martinsefcik** [comment]
@therealrinku Wouldn't it be good to have it also on Vars tab ?

**Comment by therealrinku** [comment]
@martinsefcik 
that makes sense, I added it as well.
thanks!

**Comment by helloanoop** [comment]
Thank you @therealrinku and @martinsefcik !

Merged!

**Comment by majkinetor** [comment]
It would be good to have some kind of marker such as a dot for other things, like non empty Body, Script, Doc...

**Pull request merged**
