### PR TITLE
fix (#759): fixed axios versions inconsistency

### LINKED ISSUE #759: [Bug] Axios requests in pre-request scripts behave differently in bruno-app and bruno-cli
In pre-request script I use Axios requests which uses Axios feature that if `content-type` header is set to `application/x-www-form-urlencoded` and `data` is JS object then it is automatically serialized and encoded to urlencoded format. It is documented here: https://axios-http.com/docs/urlencoded#automatic-serialization and it should be available in Axios (if I'm not mistaken) from version 1.0.0

But it is working as expected only in bruno-app and not working correctly in bruno-cli (data object is sent serialized as json and not urlencoded)

Minimal request how to reproduce it:
```
meta {
  name: test
  type: http
  seq: 1
}

get {
  url: https://www.google.com
  body: none
  auth: none
}

script:pre-request {
  const axios = require('axios');
  let res = await axios({
    url: 'https://webhook.site/ce3d32c9-dbc1-42b5-8894-195beb0bdfea',
    method: 'post',
    data: {
      grant_type: 'client_credentials'
    },
    headers: {
      'content-type': 'application/x-www-form-urlencoded'
    }
  });
}
```

I can see on webhook.site that if such request is executed in bruno-app, then raw request body is:
```
grant_type=client_credentials
```

If I run this request in bruno-cli then the raw body is:
```
{
  "grant_type": "client_credentials"
}
```

bruno-app version: 0.27.0
buno-cli version: 0.15.1

### PR DESCRIPTION
**Pull request by martinsefcik**
# Description

Fixes #759.

Inconsistency of Axios versions defined in Bruno packages.  Then axios requests can behave differently in bruno-cli and bruno-app both executed from official binaries or also differently in bruno-app executed from binaries and bruno-app executed from the sources.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

### CODE REVIEW

**Comment by martinsefcik** [comment]
@helloanoop any chance to have it merged soon ? It blocks us to use our big production collection with bruno-cli

**Comment by helloanoop** [comment]
@martinsefcik This is now released in `v1.1.1` 🎉

**Comment by martinsefcik** [comment]
@helloanoop thanks but important for me is to have it released in ` bruno-cli` and there is the latest version 1.0.0 I expect without this fix.

**Comment by helloanoop** [comment]
@martinsefcik I just released `bruno-cli` `v1.1.0` which uses `axios 1.5.1`

**Comment by martinsefcik** [comment]
@helloanoop I appreciate your effort but it still does not work, probably because published `@usebruno/js` `0.9.1` npm package does not contain changes I did in this PR in this package. So I think it is needed to release new `0.9.2` version of `@usebruno/js` then use this `0.9.2` version in `bruno-cli` and then do new release `@usebruno/cli` `1.1.1`

It can be then easily tested by putting the following code in any request's pre-request script:
```js
console.log(axios.defaults.transformRequest.toString())
```
if it prints this:
```js
function transformRequest(data, headers) {
    normalizeHeaderName(headers, 'Accept');
    normalizeHeaderName(headers, 'Content-Type');

    if (utils.isFormData(data) ||
      utils.isArrayBuffer(data) ||
      utils.isBuffer(data) ||
      utils.isStream(data) ||
      utils.isFile(data) ||
      utils.isBlob(data)
    ) {
      return data;
    }
    if (utils.isArrayBufferView(data)) {
      return data.buffer;
    }
    if (utils.isURLSearchParams(data)) {
      setContentTypeIfUnset(headers, 'application/x-www-form-urlencoded;charset=utf-8');
      return data.toString();
    }
    if (utils.isObject(data) || (headers && headers['Content-Type'] === 'application/json')) {
      setContentTypeIfUnset(headers, 'application/json');
      return stringifySafely(data);
    }
    return data;
  }
```
then some pre 1.0.0 version of axios was bundled in bruno-cli (current state with bruno-cli 1.1.1)

If it prints more complex implementation of default request transform function (with support for transforming url form encoded data):
```js
function transformRequest(data, headers) {
    const contentType = headers.getContentType() || '';
    const hasJSONContentType = contentType.indexOf('application/json') > -1;
    const isObjectPayload = utils.isObject(data);

    if (isObjectPayload && utils.isHTMLForm(data)) {
      data = new FormData(data);
    }

    const isFormData = utils.isFormData(data);

    if (isFormData) {
      if (!hasJSONContentType) {
        return data;
      }
      return hasJSONContentType ? JSON.stringify(formDataToJSON(data)) : data;
    }

    if (utils.isArrayBuffer(data) ||
      utils.isBuffer(data) ||
      utils.isStream(data) ||
      utils.isFile(data) ||
      utils.isBlob(data)
    ) {
      return data;
    }
    if (utils.isArrayBufferView(data)) {
      return data.buffer;
    }
    if (utils.isURLSearchParams(data)) {
      headers.setContentType('application/x-www-form-urlencoded;charset=utf-8', false);
      return data.toString();
    }

    let isFileList;

    if (isObjectPayload) {
      if (contentType.indexOf('application/x-www-form-urlencoded') > -1) {
        return toURLEncodedForm(data, this.formSerializer).toString();
      }

      if ((isFileList = utils.isFileList(data)) || contentType.indexOf('multipart/form-data') > -1) {
        const _FormData = this.env && this.env.FormData;

        return toFormData(
          isFileList ? {'files[]': data} : data,
          _FormData && new _FormData(),
          this.formSerializer
        );
      }
    }

    if (isObjectPayload || hasJSONContentType ) {
      headers.setContentType('application/json', false);
      return stringifySafely(data);
    }

    return data;
  }
```
then some 1.0.0+ version of axios is bundled in bruno-cli

**Comment by helloanoop** [comment]
Thanks @martinsefcik !

I've just release `v1.1.1`.

image

**Comment by martinsefcik** [comment]
@helloanoop Thank you very much, it is working fine now!

**Pull request merged**
