### PR TITLE
feat: toggle visibility of secret envVars

### LINKED ISSUE #330: [Feature Request] Show password type editor for secret environment values
I think SingleLineEditor should change to password type when "Secret" checkbox is ticked. I don't know how to do it, but when you enter this secret on the editor: banana; you should see ******.

### LINKED ISSUE #1646: Hide secrets in the UI
### Discussed in https://github.com/usebruno/bruno/discussions/1645

<div type='discussions-op-text'>

<sup>Originally posted by **warlon** February 22, 2024</sup>
If a variable is set as a secret it should also be hidden in the UI and only revealed when requested. This would add additional security and prevent secrets being leaked for example when sharing your screen with someone.</div>

### PR DESCRIPTION
**Pull request by dw-0**
# Description

Today at work i noticed, that environment variables which are configured as "secret" will be shown in plain text in the variable overview:
image
`username` and `password` are configured as secret variables.
This could lead to leaked credentials or any other secrets (there is a point why you mark them as secret right?) during MS Teams meetings while sharing you screen to other people and either want to show them something specific in that variables overview or you simply leak it by accident during other situations.

For that reason i implemented this feature. Now, by default, all secret variables are disguised by default and it requires the user to explicitly make those values visible by clicking on a new button:

23-10-17_23-23-30_electron

In case we even want to disguise the actual length of a variables value, we could refrain from using the maskValue function defined in line 14 and used in line 29 and simply replace the whole `envVar.value` by a fixed length `***********`-string for example.

Where i'm not 100% sure at the moment is the placement and visuals of the actual toggle button. I'm open to suggestions on how to improve the placement and overall visualization in the UI.

# Contribution Checklist:

- [x] **The pull request does not introduce any breaking changes**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

----
closes #330 
closes #1646

### CODE REVIEW

**Comment by pove** [comment]
Love it. Can this be also applied to the environment variable editor as well? I mean once you click on the "secret" checkbox while adding/editing variables.

There is an issue for that: #330

**Comment by dw-0** [comment]
@pove 
Ah okay, i didn't see that issue. But that probably makes sense, yes. So as soon as you tick the secret checkbox, mask the actual values with "*****" right?

**Comment by dw-0** [comment]
I pushed an update so secrets now get hidden in the env-var settings once selected as secret.
23-10-19_17-38-40_electron

I see some checks are failing, will sort that out asap.

**Comment by dw-0** [comment]
@helloanoop Hey :) Do you think this PR could make it into one of the next releases? In case you want something changed, please let me know!

**Comment by dw-0** [comment]
@helloanoop Any chance getting this merged anytime soon?

**Comment by jzorn** [comment]
Great feature, I'd love to see it too!

**Comment by MPratley** [comment]
While in the area (At the risk of burdening this PR even more):
Secrets are also currently exposed if you hover over a variable definition

Screenshot 2024-03-14 at 13 20 51
Screenshot 2024-03-14 at 13 21 08

Would probably be good to `*****` blank them there too!

**Comment by dw-0** [comment]
Good point. Unfortunately, except for one reaction to the main post, this feature doesn't seem to be getting any attention from a maintainer. Perhaps there is no real interest. This PR was assigned to a milestone (v1), but the concept of milestones does not seem to be consistently implemented, otherwise this feature would have found its way into the codebase long ago.

For this reason, I am currently less interested in continuing to work on the feature without knowing whether it will be merged in the near future. The PR has existed for almost 5 months now.

**Review by sanjai0py — APPROVED** [review]

**Comment by sanjai0py** [comment]
Hey @dw-0, thanks for the PR - the feature looks great! Can you please resolve the conflicts?

**Comment by dw-0** [comment]
I resolved the conflicts, i don't know why all tests are failing but it seems this PR is not the only one affected.

I did not manage to understand what needs to be changed to realize the proposal of @MPratley

**Pull request merged**
