### PR TITLE
feat: Store cookies received in Runner execution

### LINKED ISSUE #2682: Cookie Management does not work while running whole folder/collection
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

**If I run all requests of a folder, the cookie management does not work same as when I run the requests one by one**

**Steps to reproduce with a simple example:**

1. Delete all cookies in bottom left cookie menu.
2. Add two requests to a folder. Example: GET https://github.com
3. Run folder

**Expected:**
Cookies are provided in request headers when running folders
Example:
First response will set cookie (in example: response header includes "< set-cookie: _gh_sess=..." )
Second response will not set a cookie as it should already be provided

**Actual.**
Cookies are not provided when running folders
Example:
First response of GET https://github.com sets session cookie (in example: response header includes "< set-cookie: _gh_sess=..." )
Second response of GET https://github.com also sets session cookie, eventhough it was already set before (in example: response header includes "< set-cookie: _gh_sess=..." )

If I run the requests one by one instead of running the folder, the cookie management works as expected. 

### .bru file to reproduce the bug

Attached example collection with example requests and a test in the second
[Cookie Folder Run Test.zip](https://github.com/user-attachments/files/16334986/Cookie.Folder.Run.Test.zip)

### Screenshots/Live demo link

see provided bruno collection in attachments to reproduce the bug.

### LINKED ISSUE #2950: Runner does not respect global preferences for cookie handling
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have a folder with a couple of requests in it. When running the requests manually one by one, they just work. When running the whole folder in a Runner execution, then the requests start failing from the 2nd request on.
I checked the requests in that folder and noticed that the response of the 1st request contains a `Set-Cookie` response header. The corresponding cookie is stored in the cookie jar correctly, when I run each request manually. For subsequent requests this cookie is sent as expected.
However, in the Runner the cookie does not seem to be stored (and sent with subsequent requests).

I can reproduce the Runner behavior in the manual case, when either...
- Disable global preference "Store cookies automatically"
- Disable global preference "Send cookies automatically"
- Delete the automatically stored cookie after the first request

This makes me think that the Runner is not dealing with cookies.

I also checked the code and think that while cookies would be sent if present, they _do not get stored_ by Runner executions.

In a manual execution I find this:
(https://github.com/usebruno/bruno/blob/600940226c36d5d8ea196c137b60a74501c974f9/packages/bruno-electron/src/ipc/network/index.js#L546-L563)

In a runner execution the cookie storage part is missing after `data` and `responseTime` have been captured:
https://github.com/usebruno/bruno/blob/600940226c36d5d8ea196c137b60a74501c974f9/packages/bruno-electron/src/ipc/network/index.js#L975-L976

In fact, the Runner execution is successful, if I ran the 1st request manually first. Then the cookie is available in the jar and used by the Runner. Therefore, the 2nd request finds the cookie and sets it correctly for the request.

### .bru file to reproduce the bug

_No response_

### Screenshots/Live demo link

no screenshots needed

### PR DESCRIPTION
**Pull request by j-lebek**
# Description

Supposed to address #2950, however, there still are some folders for which my changes do not store the cookie. Need some more analysis.

fixes #2682 
fixes #2950

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by j-lebek** [comment]
Seems like redirects are not covered yet. In fact, cookies are not stored even for manually executed requests (without Runner).
So this might be considered another bug/issue.
Therefore, I consider this PR to be final.

**Comment by nikischin** [comment]
Does this fix #2682?

**Comment by j-lebek** [comment]
> Does this fix #2682?

Yes, indeed. This seems to be the same issue. I didn't notice #2682 when opening #2950.

**Comment by nikischin** [comment]
> Yes, indeed. This seems to be the same issue. I didn't notice #2682 when opening #2950.

I would recommend adding
```
fixes #2682 
fixes #2950
```
to the description of the PR, so that those Bugs will be linked and should be automatically closed when this PR is merged.

Thank you very much and I hope this gets merged soon!

**Comment by helloanoop** [comment]
Merged!
Thanks for working on this @j-lebek !

**Pull request merged**
