### PR TITLE
feat: Feature/cli support multiple reporters

### PR DESCRIPTION
**Pull request by iamdavidfrancis**
# Description
Adding the ability to pass multiple reporters using `--format`. You can specify the output files using `--output.reporter`

Sample I ran on my machine:
`node ..\..\bruno-cli\bin\bru.js run --env Prod --output junit.xml --format junit --format html --format json --output.html html.html --output.json results.json`

Console output:
image

All 3 files were written:
image

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Related to #2045

### CODE REVIEW

**Comment by helloanoop** [comment]
Thanks for taking the time to work on this @iamdavidfrancis !

I think we need to support a simpler cli args for multiple reporters.
I penned a proposal here: #2918

**Comment by iamdavidfrancis** [comment]
@helloanoop I've pushed an update to use the schema mentioned in your discussion. Let me know if you have any thoughts.

**Comment by berlingoqc** [comment]
what needs to be done to get this merged?

**Comment by helloanoop** [comment]
@lohxt1 Can you review this please ?

**Comment by helloanoop** [comment]
Merged!
This will be available in upcoming `v1.29.0` release

**Pull request merged**
