### PR TITLE
#816 Feature: auth from collection

### LINKED ISSUE #816: Ability to override Collection Auth
1. I set the `Collection` `Auth` to `bearer token`
2. I click on a request and go to the `Auth` tab

### Expected result

I expect a list starting with `Collection default - Bearer Token` (selected), `AWS sigV4`, `Basic Auth`, `Bearer Token`, `No Auth`.

### Result

I get this list: `AWS sigV4`, `Basic Auth`, `Bearer Token`, `No Auth` (selected).

When `No Auth` is selected, the Collection default is used. I think this is confusing.

### PR DESCRIPTION
**Pull request by btgs-0**
# Description

Allows users to choose a 'From Collection' auth type for any request, similar to postman's "inherit auth from parent" auth type. New requests inherit the collection's auth mode by default. Resolves #816 and #960

image
image
image
image
image
image

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
* I'm not actually sure about this one. I am seeking input/validation because I'm not familiar with the web stack (I do C# desktop apps in my day job)
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by shille** [comment]
Could you please implement inherit from parent and support Auth at the folder level which itself could inherit from the collection being the ultimate parent?  This data is supported in Postman and is lost on import from Postman otherwise.

**Comment by btgs-0** [comment]
@shille as discussed on #816 I think you should open a new issue for that functionality. If postman has that and bruno doesn't and bruno says that it can import postman collections then I guess technically the lack of it is a bug?

**Comment by kpau** [comment]
This PR also resolves #960 
Thanks!

**Comment by GimpMaster** [comment]
Any chance we can get this PR merged?

**Comment by karloluis** [comment]
I'd be happy to close my PR https://github.com/usebruno/bruno/pull/1409 since this would also address the issue it solves, which is a side-effect of how axios handles `auth` vs `headers.authorization` from the request configuration.

**Comment by btgs-0** [comment]
looks like #1667 fixed this

**Pull request closed without merging**
