### PR TITLE
Make sure path string does not overflow the dialog

### PR DESCRIPTION
**Pull request by gkohen**
See also: #217

### CODE REVIEW

**Comment by helloanoop** [comment]
Nice. Merged!

Thanks @gkohen !

**Comment by gkohen** [comment]
Glad I could help. I actually wanted to make Modal resizable but then I saw the whole thing was a bespoke implementation of divs. Out of curiosity, did you consider using one of the open source react libraries such as Material UI https://mui.com/material-ui/

**Comment by helloanoop** [comment]
> Out of curiosity, did you consider using one of the open source react libraries such as Material UI

This is my personal take,

Using a component library come with tradeoffs.
It empowers you to ship things fast, and offer a consistent design language for the whole app.

But the downside is customizing a theme may become difficult. I wanted Bruno to be really clean, simple and compact and was willing to put in the hours to create bespoke components (tables, modals, textboxes, tabs, lists, dropdowns) and ensure that the design language is consistent.

If I was working with a big team on a large project (with no dedicated resources to design a org level component library), I would definitely research a few component libraries, find the one that fits the project needs and adopt it and ship things faster.

Bruno is a passion project, carefully hand crafted :)

**Comment by gkohen** [comment]
First of all thank you for all you have done.
Understood. As I'm trying to get my teams to switch from Postman(possible), I wanted to see if Bruno can be more resilient growing it's contributing body as well as speed of implementation to see if it's a viable solution as well as enticing more folks to contribute. Totally understand if you want to focus more on hand crafting it and maintain closer control on how things are implemented.

**Comment by helloanoop** [comment]
> Bruno can be more resilient growing it's contributing body as well as speed of implementation to see if it's a viable solution as well as enticing more folks to contribute.

At the moment at least, I'd like to maintain closer control.

Thanks for bringing up the concern however.

If you look at the current ecosystem.
- Postman - VC funded, Deletes scratchpad, Your data is in cloud, community has less say 
- Insomnia - VC funded. It's going postman's route, only UI is opensource 
- Thunder Client - Closed source. Was free for 2 years and now they are charging 
- Hoppscotch - VC funded. Yet to see how it plays out

If you get VC funding / acquired - it's just a ticking bomb.

I definitely don't want to do this.

I hope Bruno can be a shining light of how to do things differently as well as live long and serve the community in a sustainable way.

As the project gains more adoption, I will write out the long term roadmap and vision on how we all can ensure that the project can live long and what kind of a governing structure and incentives can be put in.

**Comment by gkohen** [comment]
Understood, it's more a chicken and an egg problem. Folks want to join and contribute to a community when they might have input. I'm talking about a tool that can become an industry community driven tool. If we want to grow as an open source and gain adoption it would be helpful to see how we can drive that governing structure and contribution effort which will have many players in the industry wanting to put time of their developers to contribute new features.

**Comment by helloanoop** [comment]
@gkohen I have penned some thoughts here: https://github.com/usebruno/bruno/discussions/269

Would love to hear your thoughts and perspective's in the github discussion thread.

**Pull request merged**
