### PR TITLE
feat(#1017) Added ability to clone a folder

### PR DESCRIPTION
**Pull request by StonyTV**
Hello,

This PR introduces a new feature to Bruno - the ability to clone folders directly from the user interface. This functionality aims to enhance user productivity and ease of use, especially for those who work with complex folder structures.

Issue : #1027 

### Changes Made:

**Clone Button**: Implemented a 'Clone' button in the right-click context menu for folders. This allows users to easily duplicate a folder along with all its contents.
image

**Error Handling**: Added an error message that is displayed when a user tries to clone a folder into the same location where a folder with the same name already exists. This prevents duplicate naming issues and maintains the integrity of the folder structure.
image

**Successful Cloning**: Upon successful cloning, the duplicated folder is created with all the original contents copied over.
image

### Additional Information:

Attached are images demonstrating the new 'Clone' button on a folder, the error message for duplicate folder names, and the successful creation of a cloned folder.
The code has been tested in various scenarios to ensure reliability and consistency.

### Benefits:

Streamlines the process of setting up similar environments or workflows.
Saves time and reduces manual effort in duplicating complex folder structures.
Aligns with existing 'Clone' functionality for individual requests, providing a consistent user experience.
I believe this feature will be a valuable addition to Bruno, significantly improving the user experience for those who manage extensive data and configurations.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

### CODE REVIEW

**Comment by StonyTV** [comment]
I found a path problem when cloning sub folder. I'll fix it.

**Comment by StonyTV** [comment]
I've made an update to my PR by integrating the findParentItemInCollection function, which ensures accurate results. Everything looks good from my end now.

**Comment by martinsefcik** [comment]
I would allow to duplicate folder in the same parent. Just add ` Copy` postfix to folder name the same way as Postman is doing this.

**Comment by StonyTV** [comment]
> I would allow to duplicate folder in the same parent. Just add ` Copy` postfix to folder name the same way as Postman is doing this.

It's a good idea but today we can't have 2 directories with the same name. If the user copies twice, should I add an error message? Or should I do a "folder copy 2" with an increment?

I find it good to keep the same operation as when copying a query. If we add this copy mechanism, it would also be necessary to extend it to the clone of the query in order to have something homogeneous

**Comment by martinsefcik** [comment]
Postman adds postfixes in the following form: ` Copy`, ` Copy 2`, `Copy 3`, ...

**Comment by martinsefcik** [comment]
I am not a right person to decide but personally I like more how it is working in Postman also with quick `Ctrl+C` & `Ctrl+V` shortcuts which I was using a lot for copying/duplicating request/folders.

**Comment by helloanoop** [comment]
Nice work @StonyTV ! I have merged the PR.

Thanks for your review and feedback on this @martinsefcik !

> Postman adds postfixes in the following form:  Copy,  Copy 2,  Copy 3, .

We can postfix the `{folderName} Copy` word in the modal to improve the current flow.

> I like more how it is working in Postman also with quick Ctrl+C & Ctrl+V shortcuts which I was using a lot for copying/duplicating request/folders.

I am onboard to support this too. We should be able to implement this for requests. For folders, we will have to wait until folder level view arrives.

**Pull request merged**
