### PR TITLE
Feat/api key auth

### PR DESCRIPTION
**Pull request by sanjai0py**
# Description

Resolves: #1005

https://github.com/usebruno/bruno/assets/84461672/9031f495-eb4a-4827-8e7d-5a53191e6abd

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by Its-treason** [comment]
The changes to `prepareRequest` etc. also need to be applied to the CLI

**Comment by nikischin** [comment]
Maybe it could be cool to have another Dropdown option:
- Authorization Header

which adds the key value inside Authorization header instead of creating a new Header entry. This could be easily replicated by setting the key to "Authorization: myAuthKey" but still could be useful to reduce confusion as I personally would have expected if I just selected _Header_ to have a behavior like this.

**Comment by LcTrKiD** [comment]
Is this still on track? Thanks for Bruno app you all :)

**Comment by helloanoop** [comment]
Thanks for this @sanjai0py !

**Comment by LcTrKiD** [comment]
Thanks @sanjai0py! This was a must-have for us.

**Comment by hoangquochung1110** [comment]
Thanks @sanjai0py for the contribution

**Pull request merged**
