### PR TITLE
fix #676 Interpolates collectionVariables after pre request scripts are ran

### LINKED ISSUE #676: Variable values are not interpolated
When adding a variable as Pre Request value the UI displays the values correctly in tooltips.
Info toolbox also tells that I can use any valid JS template literal.
However it doesn't interpolate the values and I end up sending literal string in request body.

image

Here's the data that i got from the GET request that I use to fetch previously saved data:

image

Here's the actual body of my request:

image

### PR DESCRIPTION
**Pull request by KaniZ0r**
# Description
Fix for https://github.com/usebruno/bruno/issues/676

All collection variables will be interpolated in the end of Pre Request script.
It will update collection variables that are not yet interpolated to proper values that are currently shown in UI.

> This issue relates to vars-runtime but the fix is done to script-runtime.
Reason for this is that users can create new variables with scripts and those variables are not available in vars-runtime because it's executed before script-runtime.

# Before
Variable values are not interpolated and sent as a literal strings

image
image

# After
Variable values are interpolated

image
image

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### CODE REVIEW

**Comment by KaniZ0r** [comment]
@helloanoop Looks like prettier fails to file this pr doesn't touch

**Comment by deanveloper** [comment]
It'd be amazing if this PR could be merged. Does this also substitute when generating code for the request?

**Comment by survivant** [comment]
@deanveloper can you check my PR, I also worked on that https://github.com/usebruno/bruno/issues/1165 or this https://github.com/usebruno/bruno/pull/1173

**Comment by helloanoop** [comment]
All collection variables are now interpolated in pre-request script.
Docs: https://docs.usebruno.com/get-started/variables/overview

Closing this PR as this is already fixed in Bruno.

**Pull request closed without merging**
