### PR TITLE
Add autocompletion for headers value

### PR DESCRIPTION
**Pull request by GuillaumeOnepilot**
# Description

Created a list of possible mime type for headers value similar to Postman. This could be improved by created a map for specific headers, but I recon it would be difficult to maintain properly

https://github.com/usebruno/bruno/assets/97881811/736bc98d-9c4f-458e-8816-006fc2d5190b

#1141 

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

### CODE REVIEW

**Comment by Its-treason** [comment]
Looks good! One thing: I would probaly move the `mimeTypes.js` one folder up into the `codemirror` folder and rename it to something like `autocompleteConstants.js`.

**Comment by GuillaumeOnepilot** [comment]
> Looks good! One thing: I would probaly move the `mimeTypes.js` one folder up into the `codemirror` folder and rename it to something like `autocompleteConstants.js`.

Make sense I will do it

**Review by Its-treason — APPROVED** [review]

**Comment by GuillaumeOnepilot** [comment]
@Its-treason Any news on this ?

**Comment by helloanoop** [comment]
Merged!
Thanks for working on this @GuillaumeOnepilot !

**Pull request merged**
