### PR TITLE
Building electron script in js to support different OS

### PR DESCRIPTION
**Pull request by survivant**
I created a node js script instead of a bash script.  I'm on Windows and running the script in cygwin or wsl is something painful.  Instead  this node js script will works on any OS.

I also generate the distribution based on the OS.  By default it was MAC.

### CODE REVIEW

**Comment by helloanoop** [comment]
Nice work @survivant !

Need to get a release out tomorrow. Will get this merged after that.

**Comment by survivant** [comment]
please, can you add this label at the end : hacktoberfest-accepted   (it's just for fun.. there are no t-shirt this year :( )

**Comment by survivant** [comment]
there are my first PR for a React project, so maybe there will need a little review, just to be sure that they respect React good pratice.

**Comment by helloanoop** [comment]
Something seems off here.

This got reverted: https://github.com/usebruno/bruno/commit/5ef0de2e4d2e8f4e42e667ae5b7af0e3bebb2754

@survivant if you don't mind, please raise a new PR

**Pull request merged**
