### PR TITLE
Fix #437 (start/endWith assertions)

### LINKED ISSUE #437: The "startWith" and "endWith" assertions do not work
image

assert {
  res.status: 200
  res.body.data.url: startsWith "https://gateway.test.com"
}

https://github.com/usebruno/bruno/blob/6db36513c50a7af2d4c58b35d017db81ff0ca43b/packages/bruno-js/src/runtime/assert-runtime.js#L265

I don't see those assertions in the chai library but in the chai-string library: https://www.chaijs.com/plugins/chai-string/

Also, apparently the syntax should be : expect('abcdef').to.startsWith('abc');

### PR DESCRIPTION
**Pull request by Sl-Alex**
This PR adds and enables "chai-string" plugin, making "startWith"/"endWith" assertions work.

### CODE REVIEW

**Comment by Sl-Alex** [comment]
Should I also push my auto-generated ```package-lock.json``` to make unit tests work?
I'm not sure if it is really needed

**Comment by grubersjoe** [comment]
@Sl-Alex yes, you should also commit the updated `package-lock.json` whenever dependencies change. More background here: https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json

**Comment by Sl-Alex** [comment]
@grubersjoe Thank you, updated it

**Comment by helloanoop** [comment]
Nice.

Thanks for taking care of this @Sl-Alex !

**Pull request merged**
