### PR TITLE
Restructure and merge documentation files

### LINKED ISSUE #784: Organize Readme's and Contributing Docs
As we add more locale's for readme, contributing and development guide, the files at root are getting bigger.
We need to move them into a separate folder.

We also need to merge the `contributing.md` and `docs/development.md` into `contributing.md`

### Proposed structure

```bash
| - readme.md
| - contributing.md
| - readme
  | -- readme_de.md
  | -- readme_fr.md
| - contributing
  | -- contributing_de.md
  | -- contributing_fr.md
```

### PR DESCRIPTION
**Pull request by areebniyas**
# Description

Since more locale's are being added, the files at root are getting bigger so this PR restructures the folders for the documentation files and merges `contributing.md` and `docs/development.md` into `contributing.md`.

Resolves #784 

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by areebniyas** [comment]
Hi @helloanoop, Can I get some feedback on this?

**Comment by helloanoop** [comment]
Thanks for taking care of this @areebniyas !

**Comment by areebniyas** [comment]
No worries @helloanoop! Would be great if you could add the `hacktoberfest-accepted` label. Cheers.

**Comment by martinsefcik** [comment]
@helloanoop I saw you additionally fixed broken links, but links to images are also broken.

**Pull request merged**
