### PR TITLE
Add initial multipart form file upload support

### PR DESCRIPTION
**Pull request by mkdillard**
This PR attempts to implement Multipart Form Data file uploads as discussed in #195

The code should handle file paths relative to the root of the current collection as well as absolute paths.

single file:
```
body:multipart-form {
  action: print
  file: @file(test.txt)
}
```

multiple files should be presented in a comma delimited list.
```
body:multipart-form {
  files: @files(test.txt,C:\Users\User\Documents\temp.txt)
  action: fax
}
```

Things still missing or potentially missing:

- I didn't see any test files explicitly for the surrounding code, I wasn't sure exactly where I should add test cases for this if any.
- I didn't add any this information to the docs, I wasn't sure where the updates should go, I saw several docs folders, but none of them looked like the docs on the site
- I didn't handle the UI updates to look nice, the value in the UI looks the same as it does in the .bru files
image

### CODE REVIEW

**Comment by jaktestowac** [comment]
Any updates on that?

**Comment by kingzcheung** [comment]
Why hasn't such a good idea been merged？

**Comment by helloanoop** [comment]
This will be a priority to get merged this week.

Current workaround is to use scripting: https://github.com/usebruno/bruno/discussions/385#discussioncomment-7196674

**Review by kym6464 — CHANGES_REQUESTED** [review]
I can think of a few counterexamples that would cause the file path parsing to fail:

1. `some file (latest).mp4` — Parentheses in filenames are fairly common
2. `hello, world.txt` — Commas are totally valid as well 🤷‍♂️

I was able to fix 1 but 2 would require file paths to be surrounded by quotes (ie CSV rules) which, based on some discussions I've read, seems like this project is not fond of since it harms readability. So I didn't wanna adjust the syntax until we've settled on an approach. I would suggest this:

```
body:multipart-form {
  action: print
  file: @file(foo.txt)
  file: @file(bar.txt)
}
```

which avoids the need for CSV rules and parsing, and keeps it nice and readable. However, I'm not sure if the DSL supports this kind of syntax. @helloanoop thoughts?

@mkdillard RE "I wasn't sure exactly where I should add test cases for this if any" I think this is a good piece of logic to test:

```javascript
const assert = require("node:assert");

/**
 *
 * @param {string} value
 * @returns {?string[]}
 */
function parsePaths(value) {
  if (!(value && typeof value === "string")) {
    return;
  }

  if (value.slice(0, 6) === "@file(") {
    value = value.slice(6);
  } else if (value.slice(0, 7) === "@files(") {
    value = value.slice(7);
  } else {
    return;
  }

  if (value.at(-1) !== ")") {
    return;
  }

  const pathCsv = value.slice(0, -1).split(",");

  // TODO resolve to absolute paths, verify exists, etc

  return pathCsv;
}

const inputs = [
  "action: print",
  "@file(test.txt)",
  "@files(test.txt,C:\\Users\\User\\Documents\\temp.txt)",
  "@file(some file (latest).mp4)",
  "action: fax",
];

const expectations = [
  undefined,
  ["test.txt"],
  ["test.txt", "C:\\Users\\User\\Documents\\temp.txt"],
  ["some file (latest).mp4"],
  undefined,
];

inputs.forEach((input, i) => {
  const expected = expectations[i];
  const actual = parsePaths(input);
  assert.deepStrictEqual(actual, expected);
});
```

**Comment by this-rafael** [comment]
Good morning, does anyone have any updates on this topic? Apparently, this valuable feature is already prepared, just waiting to be released. :cry:

**Comment by gseroul** [comment]
I just discovered Bruno and did everything to import all my postman collection to Bruno. It is workijng well, fantastic software !  But I really miss the file upload, actually I have to keep Postman just for this. Script is not an option for us.
This file upload option is a must have to kick Postman out and free all of us ;-)

**Comment by Poltuu** [comment]
don't make me create a postman account over this 🙏  😭 🙏

**Comment by helloanoop** [comment]
Thank you for work on this @mkdillard ! 
Your work was an inspiration for the PR #1130 which has been merged.

File Uploads are available in Bruno `v1.8.0` 🥳

**Pull request closed without merging**
