### PR TITLE
Draft: Feature : Add Vault integration

### PR DESCRIPTION
**Pull request by Oryss**
# Description

This PR adds Vault variables interpolation. 

**What is Vault?**

HashiCorp Vault is an identity-based secrets and encryption management system. It provides encryption services that are gated by authentication and authorization methods to ensure secure, auditable and restricted access to secrets. It is used to secure, store and protect secrets and other sensitive data using a UI, CLI, or HTTP API.

[More informations](https://developer.hashicorp.com/vault/docs/what-is-vault)

This lets you use your Vault KV _(key/value)_ secrets in your requests by using the following format :

```
{{vault|path|jsonPath}}
```

## Todo

- [x] Add caching so it does not make the requests every time.
- [ ] Fix error when generating code

## Notes

- I have added a documentation file so you can use a dev Vault setup to test the PR
- I chose the {{vault|foo|bar}} format so it can be considered as valid JSON in CodeMirror when inside strings.
- I am not using a Handlebars template + compile, because it does not support promises (I don't want to add an extra library for this)
- Same issue with the removal of a `forOwn` in packages/bruno-electron/src/ipc/network/interpolate-vars.js, it created issues that were hard to debug

## Screenshots

Using {{vault}} inside Body.

image

Using {{vault}} inside Query.

image

Environment configuration.

image

Using {{vault}} in pre-request variables

image

Using env variables inside {{vault}}

image

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

closes https://github.com/usebruno/bruno/issues/792

### CODE REVIEW

**Comment by Oryss** [comment]
I'm putting the PR in draft, I will simplify the code and feature so it's easier to review

**Comment by NicklasWallgren** [comment]
Why was this PR closed?

**Comment by Oryss** [comment]
> Why was this PR closed?

The code is probably too bad to be in the codebase. and it was crashing when generating code. I don't think I did it the right way. I just wrote a script based on vault.js from this PR and added a collection-level script so it works the same way as this PR, which is enough for our usage.

I noticed Vault integration will be in the paid edition of Bruno so I'll just use our custom script and wait until the real integration

**Comment by helloanoop** [comment]
Hi @Oryss It would be great if you could post your vault script at https://github.com/usebruno/bruno/discussions/385

It could help others who are looking to integrate Vault via scripting approach.

**Pull request closed without merging**
