### PR TITLE
insomnia-importer: import environments

### PR DESCRIPTION
**Pull request by petoc**
Import environments.

### CODE REVIEW

**Comment by helloanoop** [comment]
@petoc 

Thank you for the PR!

Just a quick question, Have we taken care of converting insomnias nested variables and replace `.` with `_`

As in `auth.token -> auth_token`
The expected behaviour is that env vars should follow javascript's variable naming validation which is

*Variable Names Must Start with a Letter, Underscore (_), or Dollar Sign ($)*

Also See https://github.com/usebruno/bruno/issues/345

**Comment by petoc** [comment]
Sorry about that I was not aware of that, thanks for pointing that out. Updated PR to address this.
- environment variables (objects/arrays) should be flattened
- variables in body/query/auth/headers are normalized too

I suppose there will be some issues with variables due to nested environments in Insomina (i.e. one variable from Base Environment and other from Sub Environment in one request), but it should be resolved in Bruno v2 (#292).

**Comment by petoc** [comment]
@helloanoop if there is anything else you would like to address, please let me know.

I noticed that there is already issue #472 which should be solved by this PR.

**Comment by F0rce** [comment]
LGTM 🎉

**Comment by ItsJustRuby** [comment]
@petoc Could you please resolve the conflicts on this branch?
I am looking forward to this being merged 😊.

**Comment by petoc** [comment]
Updated, but it is up to @helloanoop if it will be merged.

**Pull request closed without merging**
