### PR TITLE
Added a setting that allows you to change the font of the code

### PR DESCRIPTION
**Pull request by qweme32**
Preview
electron_Msz4JnnuKO

### CODE REVIEW

**Comment by qweme32** [comment]
I may move this setting to the "Theme" section, that seems more logical to me, what do you think @helloanoop ?

**Comment by helloanoop** [comment]
Nice.

@qweme32 Is it possible to load the fonts from the system and display them as a dropdown to choose from ?

**Comment by qweme32** [comment]
> Nice.
> 
> @qweme32 Is it possible to load the fonts from the system and display them as a dropdown to choose from ?

image
@helloanoop Yes, I found a function that returns all local fonts, but there is one thing - there are too many of them (300+ in my case), you need to do a full search on them. Also the user will use only monospaced fonts in the code. Of course I can build such a form, but is it worth it, I think it's better to leave just the input and not to load ui.

**Comment by qweme32** [comment]
@helloanoop any comments?

**Comment by helloanoop** [comment]
Sure @qweme32 

I have one comment post that we can merge this. Can you update the input box styling to match the theme, You can take a look at the input boxes in `New Request` / `Rename Request` components ?

**Comment by qweme32** [comment]
@helloanoop 

Dark
image

Light
image

**Comment by helloanoop** [comment]
@qweme32 Thank you for your patience. I know you would like to get this merged. I have shipped key bug fixes today. Will visit this tomorrow.

**Comment by qweme32** [comment]
@helloanoop it's been 3 days

**Review by newtoallofthis123 — APPROVED** [review]
lgtm

**Comment by dw-0** [comment]
Having to type in a font name seems like bad UX to me. 

> Also the user will use only monospaced fonts in the code.

I don't think that all users want monospaced fonts if they get the chance to change the font.

Is having 300+ fonts installed a regular thing?

**Review by BoscoDomingo — APPROVED** [review]
This looks good, can we get it merged? The default font is kinda ugly!

**Pull request merged**
