### PR TITLE
Feat(#736): ctrl tab shortcut

### PR DESCRIPTION
**Pull request by Jeremie-Chauvel**
# Description
Briefly, I added a ctrl-tab behavior to Bruno with a dedicated UI (a popup to show which tab to switch to)

To do so I had to store a stack of recent tabs in order and I added a component for the UI.

I had to extract the special tabs names map to allow usage in the ctl tab feature and tweaked the name of the collection setting tab which was (in my opinion) not descriptive enough. 

I added a jest config to test my feature as I needed module path resolution
  

Issue: https://github.com/usebruno/bruno/issues/736

https://github.com/usebruno/bruno/assets/28385941/009c1741-fb14-4782-b555-7ac668238ff2

---

~One thing I'm thinking about** is I only added the collection name in addition to the tab name, but we might want complete path (folders) as well~-> well I did it as it felt important for large collections

https://github.com/usebruno/bruno/assets/28385941/c61f908f-edb1-44e9-b9dc-29c2d0f226a1

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by Jeremie-Chauvel** [comment]
I added folder path to ctrl Tab as it felt needed for large collections:

https://github.com/usebruno/bruno/assets/28385941/253e099b-827b-44ea-9232-bd00e6e68622

**Review by flof — APPROVED** [review]

**Comment by Jeremie-Chauvel** [comment]
Hi @helloanoop,

just rebased this pr I made some time ago that add ctrl+tab to the Bruno electron interface since it's a feature I missed quite a lot when I switched from Insomnia to Bruno. Should be quite painless to merge, I tested it quite extensively again.

Cheers and a ton of strength, I just looked at the number of opened pull request :sweat_smile:

**Comment by helloanoop** [comment]
Sorry for being so late to review this @Jeremie-Chauvel !
We are reviewing this pull request. We are aligned with the UX updates that have been proposed and the `Ctrl+Tab` functionality.

We expect to have this merged in the next few days.

**Comment by helloanoop** [comment]
Thanks @Jeremie-Chauvel !

No need to rebase. I have merged them to a feature branch. There are a couple of improvements that we want to make on the state management of the tabs.  Will provide an update later today.

**Pull request merged**
