### PR TITLE
fix(#2123): Move output to stderr

### LINKED ISSUE #2123: cli: add the ability to output to /dev/stdout
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

It is helpful to print the results of a collection run to stdout, as it is currently possible via `bru run --output /dev/stdout`. Some commands are adding additional output to stdout, e.g. when running a recursive collection `Running Folder Recursively`. This output prevents output processing in a pipeline, e.g. via `bru run --output /dev/stdout | jq`. By moving the non-result output to a different output stream, e.g. stderr, pipelines would be much easier to compose.

### Mockups or Images of the feature

```
$ bru run --output /dev/stdout | jq
[ignored output on stderr]
{
  "summary": {
    "totalRequests": 1,
    "passedRequests": 1,
    "failedRequests": 0,
    "totalAssertions": 0,
    "passedAssertions": 0,
...
}
```

### PR DESCRIPTION
**Pull request by jzorn**
# Description

This change moves informational command outputs from console.log (prints on stdout) to console.warn/console.error (prints on stderr) to enable stdout processing in pipelines.

This was merged already but got reverted by @helloanoop for a second review, see the comments in #2125 
Was already approved by [andreassiegel](https://github.com/andreassiegel).

Fixes #2123
See #2125 

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by jzorn** [comment]
@andreassiegel As suggested in #2125 - thanks!

**Comment by jzorn** [comment]
@helloanoop Do you think you will find time to review this change some time soon? The problem is that the informal output of the application is polluting the json output if sent to /dev/stdout, making parsing e.g. via jq impossible.

```
bru run --output /dev/stdout | jq
jq: parse error: Invalid numeric literal at line 1, column 8
EPIPE: broken pipe, write
zsh: exit 1     bru run --output /dev/stdout |
zsh: exit 5     jq
```

**Comment by jzorn** [comment]
Gentle nudge @helloanoop :)

**Comment by jzorn** [comment]
Anything I can do to get this change merged? @helloanoop

**Comment by sanjai0py** [comment]
Hey @jzorn, thank you for your continuous interest. I apologize for the delay in merging this PR. The Bruno team is currently fully occupied with improving the security aspects of the software. I am closely monitoring this PR, so there's no need to worry. I can't provide a specific time for when this PR will be merged, but I assure you it won't be long. Once again, thank you for your patience and for creating PRs that will help improve Bruno!

**Comment by sanjai0py** [comment]
Hey, will get back to regarding the PR tomorrow.

**Comment by helloanoop** [comment]
Hey @jzorn !

I agree with @andreassiegel comment

> So, to me, this felt like a "misuse" of output streams due to the conflict between "actual" (result) output and intermediate log information

Wouldn't your use case be solved by doing 
```sh
bru run folder --output results.json
echo "results.json" | jq
```

We wouldn't want to have code like. People who will come across this code in the future will be like - "Why is it a console error instead of just a log"
```javascript
console.error(chalk.dim(chalk.grey(`Wrote results to ${outputPath}`)));
```

**Comment by jzorn** [comment]
As discussed in the other PR, mixing the actual output of the run (which belongs on STDOUT) with the "informal" messages (which belong to STDERR) is causing this problem. Those two standard pipes exist so that callers can distinguish between these classes of information. There is no benefit to the current way, as far as I can tell. Writing the result file is not an option if the application is running in a read only container, and even if the results file can be created it can cause additional work to ensure cleanup, proper rights to avoid leakage of sensitive information etc.
Please also see [this article which explains the STDERR a bit more in detail](https://web.archive.org/web/20201204114029/http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout).
If `console.error` is the problem, we can also use `console.warn`. Perhaps that's improving the situation a bit?

**Comment by andreassiegel** [comment]
@helloanoop Since you referred to me, I would also like to point you to this comment in the previous conversation: https://github.com/usebruno/bruno/pull/2125#issuecomment-2090290328

After some consideration, the suggested change makes a lot of sense.
And in contrast to that, the different log levels that would be supported have not that much meaning for a CLI tool. In that sense, I second the idea of separating output streams depending on the usage of the output. This is a perfectly valid use case, that’s also in line with documentation of the output streams.

**Comment by jzorn** [comment]
Hey everybody, is there anything else we can do to get this change merged? :)

**Comment by helloanoop** [comment]
Appreciate the comments @andreassiegel @jzorn .
I am currently refining our PR backlog, will spend some time on this later this week and come back with an update.

**Comment by jzorn** [comment]
Hey everybody, any updates on this? :)

**Comment by jzorn** [comment]
Hey, it's me again - any updates on this?

**Pull request closed without merging**
