### PR TITLE
fix #961 by using trim

### LINKED ISSUE #961: [Bug] Can not see the URL after paste on the input when copy url from network chrome
When I try to copy the API URL from `Request URL` in the `network` on Chrome then paste on URL input. We can not see the URL

https://github.com/usebruno/bruno/assets/39086067/a1b3e795-a303-4cd9-ac86-119ff43b6820

### PR DESCRIPTION
**Pull request by bennieboj**
# Description

I fixed #961 by applying .trim() on the incoming url.
Unsure if tests are used to safeguard the functionality of components, I didn't see any tests for QueryUrl, but maybe I overlooked them.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by helloanoop** [comment]
Thanks for taking care of this @bennieboj !

**Comment by helloanoop** [comment]
> Huhhmm, I think this change lead to regresstion

@namhihi237 Can you explain. I didn't get what you meant.

**Comment by helloanoop** [comment]
@namhihi237 If you mean't the regression tests getting failed, I have fixed it.

image

**Comment by helloanoop** [comment]
Sure @namhihi237 ! That's be great.

I think there might be an edge case where this breaks.

We should improve
`url: value.trim()`
to
`url: value && typeof value === 'string' ? value.trim() : value`

**Comment by bennieboj** [comment]
I'm not sure where in the architecture I should fix this.
Maybe in the SingleLineEditor itself? (As the name implies).

I changed the color of the save button to purple by accident.

I'll try to change both in a future fix.

**Pull request merged**
