### PR TITLE
Moving main actions to a new topBar instead of 3 dots menu

### PR DESCRIPTION
**Pull request by francois76**
# Description
In the current UI, the buttons that concern the whole app are positionned a bit everywhere, and it's quite confusing in my mind to find things. The goal of this PR is to propose a UI change that move main buttons on a top bar.

Relates to #813

<details>
  <summary>First proposal: top bar in the main view </summary>

Capture d’écran 2023-10-28 à 17 11 33
</details>

<details>
  <summary>Second proposal: small icons in the sidebar</summary>

Capture d’écran 2023-10-28 à 22 56 54
</details>

<details>
  <summary>Third proposal: Group of icons with labels in sidebar</summary>

Capture d’écran 2023-10-28 à 23 27 10
</details>

<details>
  <summary>Fourth proposal: a large "Collection" group with sort and filter, settings in fron of bruno logo</summary>

Capture d’écran 2023-10-29 à 12 31 09
Capture d’écran 2023-10-29 à 12 30 45
Capture d’écran 2023-10-29 à 12 30 12

</details>

### Contribution Checklist:

- [X] **The pull request only addresses one issue or adds one feature.**
- [X] **The pull request does not introduce any breaking changes**
- [X] **I have added screenshots or gifs to help explain the change if applicable.**
- [X] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [X] **Create an issue and link to the pull request.**
- [ ] **Owner validation of the design**
- [ ] **Fix text edition**
- [ ] **Fix text and labels mentionning old places**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by pove** [comment]
I have to say it is beautiful. However, it takes a lot of space and these are options you don't use a lot in the day. I prefer to have most of the space available for the request/response panel. Also scripts needs a lot of space sometimes...

**Comment by francois76** [comment]
> I have to say it is beautiful. However, it takes a lot of space and these are options you don't use a lot in the day. I prefer to have most of the space available for the request/response panel. Also scripts needs a lot of space sometimes...


Thanks for your feedback. I pushed another commit with a second proposal where the bar is in sidebar and not on main panel. It might be better, maybe. 
Capture d’écran 2023-10-28 à 22 56 54

**Comment by francois76** [comment]
and here is a third proposal :
Capture d’écran 2023-10-28 à 23 27 10

**Comment by pove** [comment]
Create, Open and Import are Collections actions, as well as Sorting action. I think these four actions (in red) should be in the already existing Collections section.

Settings and Dev tools actions could be when previous three dots are, at the right of the logo/App name.

image

I really do like to give settings gear more presence putting it at the top. Please note this recent commit
https://github.com/usebruno/bruno/commit/1f0bde4a122bbb95e4c5a63bfc1eb24611f01f2c, that adds this text:

_You can disable SSL verification in the Preferences.
To open the Preferences, click on the **gear icon in the bottom left corner**._

Other note: Why Import action has the Download icon? Better options could be:
image
image
image

[Material icons reference](https://fonts.google.com/icons?icon.query=upload).

**Comment by francois76** [comment]
> Create, Open and Import are Collections actions, as well as Sorting action. I think these four actions (in red) should be in the already existing Collections section.
> 
> Settings and Dev tools actions could be when previous three dots are, at the right of the logo/App name.
> 
> image
> 
> I really do like to give settings gear more presence putting it at the top. Please note this recent commit [1f0bde4](https://github.com/usebruno/bruno/commit/1f0bde4a122bbb95e4c5a63bfc1eb24611f01f2c), that adds this text:
> 
> _You can disable SSL verification in the Preferences. To open the Preferences, click on the **gear icon in the bottom left corner**._
> 
> Other note: Why Import action has the Download icon? Better options could be: image image image
> 
> [Material icons reference](https://fonts.google.com/icons?icon.query=upload).

Thanks for your feedback. I tried your suggestion and I really love the result. 
Capture d’écran 2023-10-29 à 12 10 25
Capture d’écran 2023-10-29 à 12 10 11
Capture d’écran 2023-10-29 à 12 09 56
For the moment the search bar is broken, I want to have a validation by the owner to finish fixing the breaking changes. 
I have taken notes about the ssh verification. For these two points. I will add tasks in this PR.
About the download icon, it's not my choice, I just taken the one from the welcoming page to keep something coherent.

**Comment by dw-0** [comment]
I would prefer to leave it as is. Personally i don't like any of the proposed solutions as all of them do not really fit well into the current design. Furthermore i don't think it's something that needs to be dealt with, as the current design is elegant and sleek.
The settings are available from the bottom left corner or (on windows) via the "Collection" menu from the menu bar.

One possible solution i can come up with is, that you do buttons (rather in gray than in blue) with either text + icon > icon > 3dot depending on how much space is available between the bruno icon and the right hand sidebar border. If it gets too narrow to display all options, collapse it back into the 3dot menu.

**Comment by francois76** [comment]
> I would prefer to leave it as is. Personally i don't like any of the proposed solutions as all of them do not really fit well into the current design. Furthermore i don't think it's something that needs to be dealt with, as the current design is elegant and sleek. The settings are available from the bottom left corner or (on windows) via the "Collection" menu from the menu bar.
> 
> One possible solution i can come up with is, that you do buttons (rather in gray than in blue) with either text + icon > icon > 3dot depending on how much space is available between the bruno icon and the right hand sidebar border. If it gets too narrow to display all options, collapse it back into the 3dot menu.

Thanks for your answer. Actually I don't understand in which way the current design is better. I agree that having a lots of buttons on the UI is not a good practice, but on the opposite, having a burger/3dots menu for three actions that we have enough space onscreen to put as single button with label is not a good idea. Moreover, I completely disagree with the idea that a setting button on the bottom left hand corner is not a good idea. This position is completely hidden and a lot of times, I missclicked on collection settings because the presentation suggests this button is for settings.

Hovever, I tried your suggestion of a gray button, it looks quite nice. I will rely on @helloanoop choice for the final PR.
Capture d’écran 2023-10-31 à 11 36 01
Capture d’écran 2023-10-31 à 11 48 33

**Comment by helloanoop** [comment]
Thanks for your work on this.

I feel the proposed changes do not fit well with the current design.
And the tradeoff of having the icons take up so much space does not justify the benefits.

Closing this PR

**Pull request closed without merging**
