### PR TITLE
bugfix/useragent-header

### LINKED ISSUE #2972: bug: userAgent in request header shows `axios`
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Current Behaviour

Currently, if you check the request header, you see that we are previewing it as axios; since `axios` is used under the hood.

### Expected Behaviour

Set `userAgent` to bruno-runtime/version_noSet `userAgent` to `bruno-runtime/version_no`, so that we can differentiate these request agents.

Example:
```
{ "level": "info", "message": "{ "timestamp ": "2024 -08 - 29T21: 37:06.281Z ", "method ": "GET ", "url ": " / health - check ", "status ": "404 ", "responseTime ": "0.420 ", "remoteAddr ": ":: 1 ", "userAgent ": "axios / 1.7.2 "}", "timestamp": "2024-08-29T21:37:06.282Z" }
```

### .bru file to reproduce the bug

_No response_

### Screenshots/Live demo link

Attaching sample screenshot for reference:

Screenshot 2024-08-30 at 3 11 55 AM

### PR DESCRIPTION
**Pull request by panda7789**
# Description
Adds bruno-specific userAgent header instead of default axios.
Fixes #2972 

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

image

### CODE REVIEW

**Comment by helloanoop** [comment]
Merged! Thanks @panda7789 !

**Comment by Minniehajj** [comment]
This PR broke the ability to set custom user agents in requests, is there any possible way to do that now?

**Comment by panda7789** [comment]
It's not possible now, maybe we can set bruno "default" userAgent only when header is empty. Do you use custom userAgent to simulate other browsers?

**Comment by helloanoop** [comment]
@Minniehajj I just merged the PR #3146 that should restore the ability to set custom user agents.
This should be available in the upcoming `v1.30.0` release next week

**Pull request merged**
