### PR TITLE
feat (#861): Add Autocomplete + JSON/JavaScript Linting

### LINKED ISSUE #861: [Feature Request] Better javascript editor for tests and scripts
Right now it is very hard to find javascript syntax errors in the test and scripts section, especially when it get's complicated.

It would be awesome to have two things:

1. syntax error check and error highlighting. Example, this should mark an error in line 1: 
```js
if (p {
 var om = 'ah';    
}
```
2. code completion suggestions, like in the developer console. for example if one types `bru.` , setVar, getVar, etc should be suggested and selectable.

That would be fantastic!

### PR DESCRIPTION
**Pull request by n00o**
Add JavaScript Autocomplete with all built-in Bruno functions. Add code linting markers for JSON and JavaScript CodeMirror sections. Add a few hotkeys to improve code editing.

# Description
Every code editor should show syntax errors and provide relevant coding autocomplete. To fix #861 these features have been added.

1. Added JavaScript and JSON invalid syntax line marker indicators.
2. Add code completion for JavaScript editor, along with built-in Bruno functions
3. Add hot-keys to improve editing and displaying JavaScript
a. `Tab` - Indent selected code
b. `Shift-Tab` - Unindent selected code
c. `Ctrl-H` - Replace text
d. `Ctrl-Space` - Autocomplete

The goal is to get this as close to VS Code as possible.

https://github.com/usebruno/bruno/assets/115114979/2c7c3b34-60bf-4321-a6b6-ebfca5d1b785

### Note:
It appears that top level awaits will show up as errors for JavaScript linter but this is a **jshint** issue that needs to be resolved. There is a open issue about this here:  https://github.com/jshint/jshint/issues/3447. It seems possible that it could be fixed at some point and we could get the feature with an update to the package.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by n00o** [comment]
It seems the autocomplete provides most of the functions that the DevTools console can see but the scripts sections can't actually use a good potion of them due to them being in VM2 (but still a decent amount of them). What are your thoughts on this @helloanoop?

Also is it worth adding the `test`, `expect` and `assert` functions to the custom autocomplete? They only work in the **Tests** tab but the autocomplete can't tell which CodeEditor component type is being made (Script/Tests/Body/Response) . Personally, I think it would make sense to include everything in the autocomplete for visibility and simplicity . Having a more customized and focused autocomplete would be something that could be added later with the introduction of a CodeEditorScript component.

**Comment by helloanoop** [comment]
@n00o This is fantastic !!

> Personally, I think it would make sense to include everything in the autocomplete for visibility and simplicity . Having a more customized and focused autocomplete would be something that could be added later with the introduction of a CodeEditorScript component.

Agreed.

> It seems the autocomplete provides most of the functions that the DevTools console can see but the scripts sections can't actually use a good potion of them due to them being in VM2 (but still a decent amount of them). What are your thoughts on this @helloanoop?

For now, I think its fine. We can consider customising this later.

PR ready to merge. Just one comment.
@n00o I see we have two addition packages `file` and `system`.
Is this needed?

**Comment by n00o** [comment]
I tried removing them but it seems that both `file` and `system` are needed for `jsonlint` to work. I am not sure if there is a better way to show they are dependencies for jsonlint (still new to this npm stuff).

Also @helloanoop, should I include `test`, `expect` and `assert` for this pull request or are you ready to merge it in now?

**Comment by helloanoop** [comment]
> I tried removing them but it seems that both file and system are needed for jsonlint to work. I am not sure if there is a better way to show they are dependencies for jsonlint (still new to this npm stuff).

Ideally, `jsonlint` should take care of this in its dependencies. I see the last package published was 6 years ago

Looking into its source code.
`require("file")` - https://github.com/zaach/jsonlint/blob/f6624322e6ba7c2c6e7848729f7309873329e7cb/lib/jsonlint.js#L424 
`require("system")` - https://github.com/zaach/jsonlint/blob/master/lib/jsonlint.js#L429-L431

I think this is fine for now. Created this issue to track it - #985

> Also @helloanoop, should I include test, expect and assert for this pull request or are you ready to merge it in now?

I will merge this PR. You can create a f.ollowup PR to include test, expect and assert

**Pull request merged**
