### PR TITLE
Add keyboard shortcut window in preferences

### LINKED ISSUE #923: Add keyboard shortcut tab to preferences window
Add a new tab in the preferences window that shows all the available keyboard shortcuts, possibly with a default option. This is useful so that users can get an overview of all possible keyboard shortcuts. This is in my opinion also a prerequisite for fully customizable keyboard shortcuts as described in #561.

For reference some keyboard shortcut windows from other electron tools.

**VSCode** 
image

**Obsidian**
image

### PR DESCRIPTION
**Pull request by MaikelH**
# Description
Add a new tab to the preference modal that displays all available keyboard shortcuts. 

To make iterations over the existing keyboard shortcuts easier, I have moved the shortcut definitions to a JSON file called `keyMapping.js`. This file contains a JSON object where every key is an action to which a keyboard shortcut can be mapped. In the `HotKeysProvider`, all hard-coded keyboard shortcuts are replaced by a reference to this file. This is a temporary solution until we have an implementation for custom keyboard shortcuts that also allow saving to a file.

Screenshot of current implementation:
image

### Todo Items
- [ ] Remove `package-lock.json` from PR
- [ ] Use icons instead of text for keyboard shortcuts

### Contribution Checklist:

- [x ] **The pull request only addresses one issue or adds one feature.**
- [x ] **The pull request does not introduce any breaking changes**
- [x ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x ] **Create an issue and link to the pull request.**

Closes #923

### CODE REVIEW

**Review by uxg21 — APPROVED** [review]

**Comment by grubersjoe** [comment]
I think there are some more shortcuts for menu entries. For example `cmd+,` to open the preferences:
https://github.com/usebruno/bruno/blob/ba761098be216e802399e8888974377fbe6bbe4b/packages/bruno-electron/src/app/menu-template.js#L17

**Comment by martinsefcik** [comment]
I guess Mac users do not want to see shortcuts with Ctrl and Windows\Linux users do not want to see shortcuts with Cmd, so it should be displayed dynamically based on the OS in UI.

**Comment by MaikelH** [comment]
> I think there are some more shortcuts for example in the menu `cmd+,` to open preferences.
> 
> https://github.com/usebruno/bruno/blob/ba761098be216e802399e8888974377fbe6bbe4b/packages/bruno-electron/src/app/menu-template.js#L17

Good catch. I will try to do another search through the codebase to find other shortcuts. Unfortunately at the moment it looks like there is not one place for all keyboard shortcuts.

> I guess Mac users do not want to see shortcuts with Ctrl and Windows\Linux users do not want to see shortcuts with Cmd, so it should be displayed dynamically based on the OS in UI.

That would be nice. I will have a look to see if this can be achieved easily.

**Comment by helloanoop** [comment]
This has been delivered as a part of #3204
Closing this PR

**Pull request closed without merging**
