### PR TITLE
proxy settings on global and collection level

### PR DESCRIPTION
**Pull request by mirkogolze**
#568 #224
proxy settings on global and collection level

@helloanoop: Please make a tool tip information for the config property.
image

### CODE REVIEW

**Comment by mirkogolze** [comment]
Hi @helloanoop,

pull request: https://github.com/usebruno/bruno/pull/617 should be included in my PR.

**Comment by helloanoop** [comment]
Hey Mirko!

This is great! Thanks for taking so much time to work on this to support App Level Proxy Settings, Adding validation and also refactoring some code in the electron ipc network, and many other touches❤️

There are some things I don't concur on the implementation (specially around preferences store). It will likely require a lot of back and forth to discuss this. And this being a long PR, it'll need to be synced many times as other PR's get merged.

So, I am going to merge this now, and make some updates on main. You can raise a separate PR post that if you feel there was something I missed.

Thanks again for getting this done!

**Comment by mirkogolze** [comment]
I think you mean the preferences object in the store. I prefer to have the logic more separated. 
And the usage of the configuration only needs to call the function. E.g. `preferences.isTlsVerification`.
I don't prefer to work on property level on the last level. For a store it is quit easy. 
I you have more complex logic, you only have to change the `isTlsVerification` and not the many places where it is used.
But here you are the boss.

**Comment by mirkogolze** [comment]
Currently I think the proxy configuration is not enabled for `fetch-gql-schema`. I think all the request preparation is necessary too.

**Comment by helloanoop** [comment]
@mirkogolze 

When it comes to state management, there are three ways in which Bruno does this
1. For requests (.bru files) and bruno.json. The state gets written into the file, the watcher(main) picks it up and emits an event, the renderer listens and update the store

2. For many other things such as responses, opened tabs, current environment, ongoing collection runs etc - the state is maintained in redux itself (This state vanishes when the app closes)

3. For Preferences, the way it is implemented is that after you click on "Save" if the ipc `save-preferences` call is successful, we update it to the redux store as you see [here](https://github.com/usebruno/bruno/blob/main/packages/bruno-app/src/providers/ReduxStore/slices/app.js#L62-L73) I don't see a need for the preferences file watcher. The preferences file is a bruno system level config that is expected to be changed only via the app only. A user should not be hand-editing this file.

Do you have a reason why we need the preferences watcher over the current way (which already works for storing TLS Validation and Font Settings) ?

**Comment by helloanoop** [comment]
> I don't prefer to work on property level on the last level. For a store it is quit easy.
I you have more complex logic, you only have to change the isTlsVerification and not the many places where it is used.

@mirkogolze I agree with you here. It makes sense to have this in a common place. I like the approach you went with.

**Comment by mirkogolze** [comment]
> Do you have a reason why we need the preferences watcher over the current way (which already works for storing TLS Validation and Font Settings) ?

For me it was the intention to have the change, when the file is changed external. Yes, of course its only for one per mill of users.

And the all watcher logic is completely on collection level. I thought it could be nice to have a global watcher level.

**Comment by helloanoop** [comment]
> For me it was the intention to have the change, when the file is changed external. Yes, of course its only for one per mill of users.

We can revisit this at some point. I still feel we should support this as users might try to mess with the preferences file and cause the app to break.

> And the all watcher logic is completely on collection level. I thought it could be nice to have a global watcher level.

I felt this too. The watcher is currently collection level stuff only.

**Comment by helloanoop** [comment]
@mirkogolze 

Overall Fantastic PR !!

I added some polish https://github.com/usebruno/bruno/commit/d809a58deb6bc1d5ea7bf3dcd4d6bd55307f976a

Changes mainly include
- Renaming `noProxy` to `bypassProxy` - Although noProxy is elegant and shorter, I felt that its better to use the same wording as we represent it in the UI and is more verbose about what the property does
- Changing `preferences` to `preferencesUtil` - The property `preferences` feels more like a set of data. I felt `preferencesUtil` is a better choice as it feels more like a set of functions

Some other points
- Totally appreciate and onboard with your efforts to refactor `configureRequest`. The file was slightly getting out of control.
- `preferencesUtil` was a really good idea and helps use a neat api to get preferences

I plan to ship a release later in the day. Let me know if there is anything that you feel we need to discuss.

**Pull request merged**
