### PR TITLE
feat: global env

### PR DESCRIPTION
**Pull request by lohxt1**
~ global environments

https://github.com/user-attachments/assets/2cd2b8af-cec0-4b6a-b9d4-8515035805bb

### CODE REVIEW

**Comment by codewell-learning** [comment]
Excellent feature and is very demanded. Nice work!

**Comment by frdesnous** [comment]
Thanks a lot @lohxt1 , much appreciated!!! One question though: where are the global environment (.bru?) files stored? I created a new one but can't find the file

**Comment by paulrudy** [comment]
> Thanks a lot @lohxt1 , much appreciated!!! One question though: where are the global environment (.bru?) files stored? I created a new one but can't find the file

I was looking too. Found it (on macOS at least) in `~/Library/Application Support/bruno/global-environments.json`

**Comment by frdesnous** [comment]
Thanks @paulrudy. I think it would make more sense to be able to save it in a different place, like at the root of all collections for example.

**Comment by paulrudy** [comment]
> Thanks @paulrudy. I think it would make more sense to be able to save it in a different place, like at the root of all collections for example.

I agree, and I'd prefer it to be in the same format as the local environments, to allow easy import (copy/paste) from local to global, and back.

**Comment by frdesnous** [comment]
@lohxt1 I assume you are also planning to enable it in the bruno CLI and be able to run the collection with this global environment 
`bru run folder --env ../Global`

**Comment by reinharn** [comment]
Will it soon be possible to configure the storage location of the global environments?

**Comment by lundgreen-jyskebank-dk** [comment]
Hi. If I have a global environment called 'user' like:

CleanShot 2024-10-16 at 09 25 40@2x

Is it then possible to access the global variables at collection level? Like:

CleanShot 2024-10-16 at 09 30 19@2x

Usecase: ONLY set user/pwd in a global variable and then use it in all collections

**Comment by yusufmalikul** [comment]
Thanks, I don't know if we have global variables.

FYI for linux the global variables stored in `.config/bruno/global-environments.json`

**Pull request merged**
