### PR TITLE
fix(#1566): added support for Powershell code generation

### PR DESCRIPTION
**Pull request by sanjai0py**
# Description

I am adding support for generating code snippets for Powershell.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **Create an issue and link to the pull request.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by sanjai0py** [comment]
I am getting this error

**Comment by sanjai0py** [comment]
I'm having trouble generating PowerShell code with a simple body due to this error in the console. 

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at escapeString (escape.js?056a:43:1)
    at convert (common.js?aa75:42:1)
    at eval (httpsnippet.js?8e8e:238:67)
    at Array.map (<anonymous>)
```

I tried to convert the same HAR request to PowerShell using [this](https://apiembed.com/) website that internally uses `httpsnippet`.Now the website made the conversion without any error.

Link to the converted PowerShell code:
api.apiembed.com/?source=https://utfs.io/f/357b672c-6093-46bc-b286-609ba12226f7-1qf7.json&targets=powershell:webrequest,powershell:restmethod,php:curl,shell:curl

Any help is appreciated!

**Comment by stefanstranger** [comment]
Hi @sanjai0py,

How can I help?

**Comment by helloanoop** [comment]
Closing this since we now support all language targets as a part of #2991

**Pull request closed without merging**
