### PR TITLE
feat: added request tab context menu 

### PR DESCRIPTION
**Pull request by therealrinku**
# Description
resolves: #1446,
resolves: #2142 

Added request context menu to add new request, clone request, close, close to the left, close to the right, close all and close saved requests.

### Contribution Checklist:
- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

https://github.com/usebruno/bruno/assets/76877078/fa95c536-0c69-4618-ade7-4b9948136d60

### CODE REVIEW

**Comment by mig8447** [comment]
@helloanoop can this be merged? this is very useful to my workflow

**Comment by BrandonGillis** [comment]
merging this PR would close : 
- #1093
- #1105
- #715
- #1446 
- #2142 

close partially :
- #1219

**Comment by PDDStudio** [comment]
Any updates on this or something that can be helped out with to get it merged?

**Comment by PDDStudio** [comment]
@therealrinku would you mind updating your MR so the pipelines do pass?   
The feature works quite well and I'm looking forward to having this in the main branch

**Comment by PDDStudio** [comment]
@therealrinku thanks a lot for the update 👍 

@helloanoop is there anything further required where I can assist you for this MR to be merged?

**Pull request merged**
