### PR TITLE
Added possibility to save response to file

### PR DESCRIPTION
**Pull request by martinsefcik**
# Description

Implements (#539) but also allows to save any response to file (not only binary).

So it adds Save response button in ResponsePane. File name is automatically prefilled in save dialog. I am trying to get file name in the following order:
- from `content-disposition` header - so if header value is `form-data; name="attachment"; filename="document.pdf"` then filename is `document.pdf`
- or from request URL if path ends with file name (contains dot and some characters after dot and does not ends with '/') - so if URL is `http://server.com/path/subpath/image.jpg` then file is `image.jpg`
- or extension derived from content-type header - so if content type is `application/json` then filename is `response.json`, if `application/pdf` then `response.pdf`
- otherwise `response.txt`

image

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

### CODE REVIEW

**Comment by cardonator** [comment]
This is awesome, nice contribution! Postman has the concept of saving a response as an example, I wonder if that could pivot off these changes somehow. The behavior in Postman is that "Sample responses" show up as a submenu under the Request on the sidebar, and when you click it, it opens the request and response that request got. Might be a nice feature for Bruno.

**Comment by martinsefcik** [comment]
@cardonator Saving response as example is in roadmap currently for version 2
https://github.com/usebruno/bruno/discussions/384

**Comment by cardonator** [comment]
Nice, thanks for the info.

**Comment by helloanoop** [comment]
This is great @martinsefcik !

Thanks for implementing this. Merged !!

**Pull request merged**
