### PR TITLE
Feat(#1093) Added ability to open tab context menu

### PR DESCRIPTION
**Pull request by StonyTV**
Hello,

I am submitting this PR to initiate context menus for the tabs. 

# Description

As of today, I have added two simple features: New Request and Tab Clone.

image

It took me some time to find the right approach and process. In my opinion, it is quite comprehensible, relies on the state of the tabs, and respects the "separation of concerns" principle, particularly in event management.

If this PR is accepted, a significant milestone, which I believe is highly expected, will be managing tab closures (individually, all except the current one, etc.). The challenge will lie in controlling the "draft mode" with control modals. 

Please let me know your feedback if you think of a different approach.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Issue : #1093

### CODE REVIEW

**Comment by binaryfire** [comment]
Thanks for working on this. Could you add "Close all" and "Close all to the right"? Currently there's no easy way to close all open tabs.

**Comment by StonyTV** [comment]
Hello @helloanoop. For information, I updated the branch and carried out the tests. The feature still works properly and is still ready to merge. Once merged, it would add many features to this tab context menu.

**Comment by Phyziik** [comment]
Closes: #715 
Sorry, I'm trying to link this to the Feature request issue (I'm new to contributin). I was about to work on this in another branch, but then I double checked and found yours. If there is work remaining after the merge, I'll make another PR.

**Comment by helloanoop** [comment]
Closing this PR as the Tab Context Menu was implemented in #2183

**Pull request closed without merging**
