### PR TITLE
bugfix: Weird Unmovable scroll bar in the tablist section #2293

### LINKED ISSUE #2293: Weird Unmovable scroll bar in the tablist section
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

There's a scrollbar-like bar appearing in my request tablist. (Check Screenshot)
noticed this too in v1.16.1

### .bru file to reproduce the bug

_No response_

### Screenshots/Live demo link

bruno-ui-bug

### PR DESCRIPTION
**Pull request by end3rbyte**
Fixes #2293 

There is an unnecessary "overflow: scroll" and "-webkit-scrollbar {display: none }" on tabs, and scrollbars appear when a more recent version of electron is used, where -webkit-scrollbar was removed

And as discovered by @Its-treason the nix build overwrite the electron version, that explain why some users see the scrollbars

> I looked into the Nix build file: https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/br/bruno/package.nix and the electron version in indeed overwritten:
>
> https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/br/bruno/package.nix#L100-L112

The scrollbars don't appear with the current electron version thanks to :

```
&::-webkit-scrollbar {
      display: none;
    }
```
But it can be removed if "overflow: scroll" is removed

# Description

Here is the demonstration that the overflow: scroll is causing the problem

https://github.com/usebruno/bruno/assets/139650490/1c2934a3-aa76-4dc7-979a-79576e7c28d9

This second video shows that removing overflow: scroll does not change anything with the current electron version, so there is no regression.

https://github.com/usebruno/bruno/assets/139650490/2edec105-f59e-41fc-931d-670648cc2f91

### Contribution Checklist:

- [X] **The pull request only addresses one issue or adds one feature.**
- [X] **The pull request does not introduce any breaking changes**
- [X] **I have added screenshots or gifs to help explain the change if applicable.**
- [X] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [X] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by busy-panda** [comment]
Hi @helloanoop I fixed the conflicts and retested.
Could we please have this PR merged ?

**Comment by pietrygamat** [comment]
@busy-panda I think you are missing a side effect here, the overflow scroll was supposed to make the entire tab bar scrollable (using the arrow buttons or horizonal wheel). With the removal of the `overflow: scroll` the entire response pane becomes scrollable. This PR also does not fix another related issue. Look how ugly the vertical scrollbar is now present in the nav menu to the left, when I open enough folders.

https://github.com/usebruno/bruno/assets/2108093/dfdf5d6c-9d3e-42c9-a03c-8255a971e78f


I think the proper fix would be to remove the scrollbar style overwrite in /globalStyles.js:169

https://github.com/usebruno/bruno/assets/2108093/201810cb-83d2-448c-b91f-2a1df874e258

The newer electron seems to handle it internally.

**Comment by helloanoop** [comment]
Thanks for taking the time to help debug and provide a fix for this issue @end3rbyte !

We have updated the electron version which has resolved this issue. The latest version of Bruno should not have this issue.
Closing this PR.

**Comment by sanjai0py** [comment]
Closing this PR as the fix for the issue has already been made and the [v1.26.2](https://github.com/usebruno/bruno/releases/tag/v1.26.2) release contains the fix.

**Pull request closed without merging**
