### PR TITLE
feat(#BRU-7) - scrollbar styling for linux and windows

### PR DESCRIPTION
**Pull request by lohit-1**
Improved scrollbar styling for linux and windows
[scrollbar_styling.webm](https://github.com/usebruno/bruno/assets/159901171/22356698-84a0-45c4-9842-50fdfb1539d9)

### CODE REVIEW

**Comment by helloanoop** [comment]
Thanks @lohit-1 !

**Comment by cvmocanu** [comment]
@lohit-1 : is there a way to turn this off? Thin scrollbars (along with scrollbars that are not always visible) are very bad for usability.

**Comment by helloanoop** [comment]
@cvmocanu Can you share a screenshot of how the scrollbar appears on your machine. We should be able to provide a toggle to use the system scrollbar instead of overriding it (that was done as a part of this PR).

**Comment by mark99i** [comment]
> Improved scrollbar styling for linux and windows [scrollbar_styling.webm](https://github.com/usebruno/bruno/assets/159901171/22356698-84a0-45c4-9842-50fdfb1539d9)

hi, @lohit-1 
I have [previously worked](https://github.com/usebruno/bruno/pull/608) on this issue, but I have not found an idea.

could you describe in more detail how and why it works?

```css
// scrollbar styling
// the below media query target non-macos devices
// (macos scrollbar styling is the ideal style reference)
@media not all and (pointer: coarse)
```

I created a test page with this code and it showed:
Windows/Chrome: NO MAC
MacOS14.3/Safari: NO MAC
MacOS14.3/Chrome: NO MAC
Android14/Chrome: MAC
```html
<html>
<head>
    <style>
        div {
            font-size: 40;
        }
        div[data-target="no-mac"] {
            display: none;
        }

        /* win-linux only selector ??? */
        @media not all and (pointer: coarse) {
            div[data-target="mac"] {
                display: none;
            }

            div[data-target="no-mac"] {
                display: block;
            }
        }
    </style>
</head>

<div data-target="mac">MAC</div>
<div data-target="no-mac">NO MAC</div>
</html>
```

**Pull request merged**
