### PR TITLE
fix(#352): Variable interpolation for multipart form body

### PR DESCRIPTION
**Pull request by Its-treason**
- Moved creation of FormData object into interpolation phase
- BREAKING CHANGE: This means in the pre-request-script `req.body` is no longer the `FormData` object, instead it's a plain key value object (See `Input Body` in the second screenshot).

Closes: #352

---

App:
grafik

Cli: 
grafik

### CODE REVIEW

**Comment by Gabrielcefetzada** [comment]
If this PR closes the [1236](https://github.com/usebruno/bruno/issues/1236), please, could update your main conversation comment?

`Closes: https://github.com/usebruno/bruno/issues/352 and https://github.com/usebruno/bruno/issues/1236` :)

**Comment by ARESBAN** [comment]
How's it going?

**Comment by blured75** [comment]
Any progress on that ? Could be nice to have :)

**Comment by Fabrice-Deshayes-aka-Xtream** [comment]
Hello. I'm interested in this fix. Any idea when it will be merged?

**Comment by Its-treason** [comment]
I fixed the Merge conflicts. I'm not sure about the changes to all the README's i think those are made by prettier.

**Comment by mariomka** [comment]
Is there any progress on that? Can I help in any manner? It blocks us from moving from Insomnia to Bruno :S

**Comment by Andreas-Schoenefeldt** [comment]
Hi @mariomka, it is usually best to contact @helloanoop in Discord.

**Comment by xosealvarez** [comment]
Any updates?

**Comment by Its-treason** [comment]
> Any updates?

Not yet, I also need to fix merge conflicts, when this is allowed to be merged.

For now, you can download my fork, that includes this and some other merge requests, but is still 100 percent compatible with normal bruno: https://github.com/Its-treason/bruno/releases/tag/nightly

**Comment by xosealvarez** [comment]
Hi @Its-treason, your fork works really good, well done, thanks a lot

**Comment by Schoof-T** [comment]
Any updates? :) Still waiting on this before I can fully switch to Bruno!

**Comment by chriswinter90** [comment]
This is a problem for us also. I suppose we could disable the 20 or so tests for now that require this with our project but definitely a pain point.

**Comment by mleziva** [comment]
We are also waiting for this fix

**Comment by Andreas-Schoenefeldt** [comment]
I think it is already good in the latest version of Bruno - it might have been fixed by some other ticket. At least my collections are not running, but I had to enter the variables fresh after update.

**Comment by xosealvarez** [comment]
> I think it is already good in the latest version of Bruno - it might have been fixed by some other ticket. At least my collections are not running, but I had to enter the variables fresh after update.

I tried this with the latest version and the issue continues, It's not solved yet.

**Review by sanjai0py — APPROVED** [review]

**Comment by busy-panda** [comment]
@helloanoop This PR definitely needs to be merged, many people are waiting on it.
Could we please move forward with it ?

**Comment by Andreas-Schoenefeldt** [comment]
I did another ping on this topi in the Discord Bugs Channel - It is at least on the radar again 🤞.

**Comment by helloanoop** [comment]
@Its-treason Thank you so much for your work on this.

This effort is now being tracked at #3142 
We plan to have support for variable interpolation in multipart form merged and released next week.

Closing this PR.

**Pull request closed without merging**
