### PR TITLE
fix(tailwindcss-forms): messes up input fields everywhere, removed it

### PR DESCRIPTION
**Pull request by bpoulaindev**
# Description

Previously added @tailwindcss/forms, but it messes up the global input fields in the UI.
I removed it.
Also solving #1814 

image
image

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by riesinger** [comment]
You will also need to update the `package-lock.json` to resemble the removal of `@tailwindcss/forms`

**Comment by bpoulaindev** [comment]
Oh yeah i love npm 18s and warnigns everywhere 
image

**Comment by riesinger** [comment]
It seems like `@tailwindcss/forms` still wasn't removed from the `package-lock.json` 🤔

**Comment by bpoulaindev** [comment]
But it's absent from my package-lock.json ... I don't really know how to solve this, except by rebuilding my entire package lock

**Comment by riesinger** [comment]
Sorry, I just looked at the diff. And you're right, `@tailwindcss/forms` hasn't been in the `package-lock.json`.

**Pull request merged**
