### PR TITLE
feat: Add Divider component

### PR DESCRIPTION
**Pull request by iamsushantk**
# Description

Divider is a fundamental element in user interfaces used to create visual separation and hierarchy within a layout. 

This PR adds a Divider component and demonstrates its usage in following parts of the application:

- TitleBar
- RequestTabs
- EnvironmentSelector

> The themes are chosen from https://tailwindcss.com/docs/customizing-colors

Attached are the screenshots for both light and dark mode:

# Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

# Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by sanjai0py** [comment]
I haven't looked into the code yet, but my first thought upon seeing the attached images is that the opacity for the divider can be reduced, maybe to 50%?

**Comment by iamsushantk** [comment]
> I haven't looked into the code yet, but my first thought upon seeing the attached images is that the opacity for the divider can be reduced, maybe to 50%?




@sanjai0py have set the opacity to 50%. Please refer to the screenshots above. Thanks.

**Comment by helloanoop** [comment]
Hey @iamsushantk 

I am onboard with the idea that Dividers help improve visual separation and hierarchy within a layout.
Even with the added opacity for the divider, I think we would need further improvements to make the UX looks appear aesthetically clean. I currently do not have additional feedback on how to improve this.

At the moment, getting this implemented is a low priority given the current state of PR backlog. We will revisit this at some point later.

**Comment by helloanoop** [comment]
Something to consider in future is to use Native Menu provided by the OS. This https://github.com/usebruno/bruno/pull/1105/files#diff-06806ec8f9109775d07a5b223e78f2308d0811b7e78700305357adc7ec339a5d should give an idea on how to implement this

**Comment by iamsushantk** [comment]
@helloanoop I am closing this PR and will look forward to proper implementation whenever that is planned. Thanks for your inputs.

**Pull request closed without merging**
