### PR TITLE
Fix for #509: [Bug] Items in the collection list (on the left sidebar) are clicked on mouse up events 

### PR DESCRIPTION
**Pull request by shaikshahid98**
Updated onMouseup event to onClick event on Collection items.
fix for #509

### CODE REVIEW

**Comment by Its-treason** [comment]
Hey @shaikshahid98, thank you for opening a PR for this!

As I said in [my comment](https://github.com/usebruno/bruno/issues/509#issuecomment-1755803701) on the original Issue, only replacing the `onMouseUp` with `onClick` will break the right click functionality. Because `onClick` is only triggered on left-click, not on right-click.

To fix this, without breaking right click functionality, you have to create an additional `onContextMenu` callback (`onContextMenu` runs on right-click) and then run the right click code from the old `onClick` callback inside the new callback.

**Comment by game5413** [comment]
Hello @Its-treason, maybe can i take over for this issue ? right click functionality was added by myself, so i think it was my responsibility for this issue. But if @shaikshahid98 already made the changes, it was ok.

**Comment by Its-treason** [comment]
> Hello @Its-treason, maybe can i take over for this issue ? right click functionality was added by myself, so i think it was my responsibility for this issue. But if @shaikshahid98 already made the changes, it was ok.

Hey @game5413, I see why you want to take over this issue, but at the same time I want to give @shaikshahid98 a fair chance to make his contribution.

I would say if he doesn't update his PR with comments/commits by tomorrow you can work on this.

**Comment by game5413** [comment]
> I would say if he doesn't update his PR with comments/commits by tomorrow you can work on this.

Hello @Its-treason , it seems @shaikshahid98 doesn't update his PR so i've create another PR #599  for the issue.

**Comment by helloanoop** [comment]
Closing this as this has been addressed in https://github.com/usebruno/bruno/pull/599

**Pull request closed without merging**
